<a href="https://colab.research.google.com/github/rivzadrian/H8_36/blob/master/H8Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment

In [2]:
import numpy as np
import pandas as pd

In [3]:
ls

drive/  sample_data/

In [4]:
df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/datasets/ggplay/googleplaystore.csv')

In [5]:
df.head()

                                                 App  ...   Android Ver
0     Photo Editor & Candy Camera & Grid & ScrapBook  ...  4.0.3 and up
1                                Coloring book moana  ...  4.0.3 and up
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ...  4.0.3 and up
3                              Sketch - Draw & Paint  ...    4.2 and up
4              Pixel Draw - Number Art Coloring Book  ...    4.4 and up

[5 rows x 13 columns]

In [6]:
df.shape

(10841, 13)

In [7]:
df.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [8]:
df.dropna(how = 'any', inplace = True)

In [9]:
df.shape

(9360, 13)

In [10]:
df.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       0
Android Ver       0
dtype: int64

In [11]:
df['Category'].unique()

array(['ART_AND_DESIGN', 'AUTO_AND_VEHICLES', 'BEAUTY',
       'BOOKS_AND_REFERENCE', 'BUSINESS', 'COMICS', 'COMMUNICATION',
       'DATING', 'EDUCATION', 'ENTERTAINMENT', 'EVENTS', 'FINANCE',
       'FOOD_AND_DRINK', 'HEALTH_AND_FITNESS', 'HOUSE_AND_HOME',
       'LIBRARIES_AND_DEMO', 'LIFESTYLE', 'GAME', 'FAMILY', 'MEDICAL',
       'SOCIAL', 'SHOPPING', 'PHOTOGRAPHY', 'SPORTS', 'TRAVEL_AND_LOCAL',
       'TOOLS', 'PERSONALIZATION', 'PRODUCTIVITY', 'PARENTING', 'WEATHER',
       'VIDEO_PLAYERS', 'NEWS_AND_MAGAZINES', 'MAPS_AND_NAVIGATION'],
      dtype=object)

In [12]:
df['Genres'].unique()

array(['Art & Design', 'Art & Design;Pretend Play',
       'Art & Design;Creativity', 'Auto & Vehicles', 'Beauty',
       'Books & Reference', 'Business', 'Comics', 'Comics;Creativity',
       'Communication', 'Dating', 'Education;Education', 'Education',
       'Education;Creativity', 'Education;Music & Video',
       'Education;Action & Adventure', 'Education;Pretend Play',
       'Education;Brain Games', 'Entertainment',
       'Entertainment;Music & Video', 'Entertainment;Brain Games',
       'Entertainment;Creativity', 'Events', 'Finance', 'Food & Drink',
       'Health & Fitness', 'House & Home', 'Libraries & Demo',
       'Lifestyle', 'Lifestyle;Pretend Play',
       'Adventure;Action & Adventure', 'Arcade', 'Casual', 'Card',
       'Casual;Pretend Play', 'Action', 'Strategy', 'Puzzle', 'Sports',
       'Music', 'Word', 'Racing', 'Casual;Creativity',
       'Casual;Action & Adventure', 'Simulation', 'Adventure', 'Board',
       'Trivia', 'Role Playing', 'Simulation;Education',
       'Action;Action & Adventure', 'Casual;Brain Games',
       'Simulation;Action & Adventure', 'Educational;Creativity',
       'Puzzle;Brain Games', 'Educational;Education', 'Card;Brain Games',
       'Educational;Brain Games', 'Educational;Pretend Play',
       'Entertainment;Education', 'Casual;Education',
       'Music;Music & Video', 'Racing;Action & Adventure',
       'Arcade;Pretend Play', 'Role Playing;Action & Adventure',
       'Simulation;Pretend Play', 'Puzzle;Creativity',
       'Sports;Action & Adventure', 'Educational;Action & Adventure',
       'Arcade;Action & Adventure', 'Entertainment;Action & Adventure',
       'Puzzle;Action & Adventure', 'Strategy;Action & Adventure',
       'Music & Audio;Music & Video', 'Health & Fitness;Education',
       'Adventure;Education', 'Board;Brain Games',
       'Board;Action & Adventure', 'Board;Pretend Play',
       'Casual;Music & Video', 'Role Playing;Pretend Play',
       'Entertainment;Pretend Play', 'Video Players & Editors;Creativity',
       'Card;Action & Adventure', 'Medical', 'Social', 'Shopping',
       'Photography', 'Travel & Local',
       'Travel & Local;Action & Adventure', 'Tools', 'Tools;Education',
       'Personalization', 'Productivity', 'Parenting',
       'Parenting;Music & Video', 'Parenting;Brain Games',
       'Parenting;Education', 'Weather', 'Video Players & Editors',
       'Video Players & Editors;Music & Video', 'News & Magazines',
       'Maps & Navigation', 'Health & Fitness;Action & Adventure',
       'Educational', 'Casino', 'Adventure;Brain Games',
       'Lifestyle;Education', 'Books & Reference;Education',
       'Puzzle;Education', 'Role Playing;Brain Games',
       'Strategy;Education', 'Racing;Pretend Play',
       'Communication;Creativity', 'Strategy;Creativity'], dtype=object)

In [13]:
df.Type.unique()

array(['Free', 'Paid'], dtype=object)

# Highest and Lowest apps

In [14]:
apps_paid = df[df['Type']=='Paid']

In [15]:
apps_paid.head()

                                               App  ... Android Ver
234  TurboScan: scan documents and receipts in PDF  ...  4.0 and up
235                 Tiny Scanner Pro: PDF Doc Scan  ...  3.0 and up
290  TurboScan: scan documents and receipts in PDF  ...  4.0 and up
291                 Tiny Scanner Pro: PDF Doc Scan  ...  3.0 and up
427                             Puffin Browser Pro  ...  4.1 and up

[5 rows x 13 columns]

In [16]:
apps_paid.Price = apps_paid.Price.apply(lambda x: x.replace('$',''))

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:5303: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [17]:
apps_paid.head()

                                               App  ... Android Ver
234  TurboScan: scan documents and receipts in PDF  ...  4.0 and up
235                 Tiny Scanner Pro: PDF Doc Scan  ...  3.0 and up
290  TurboScan: scan documents and receipts in PDF  ...  4.0 and up
291                 Tiny Scanner Pro: PDF Doc Scan  ...  3.0 and up
427                             Puffin Browser Pro  ...  4.1 and up

[5 rows x 13 columns]

In [18]:
apps_paid.Price = apps_paid.Price.apply(lambda x: float(x))

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:5303: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [19]:
apps_paid.Price.max()

400.0

In [20]:
apps_paid.Price.min()

0.99

In [21]:
apps_paid[
          apps_paid['Price'] == 400
]

                           App   Category  ...  Current Ver Android Ver
4367  I'm Rich - Trump Edition  LIFESTYLE  ...        1.0.1  4.1 and up

[1 rows x 13 columns]

List apps dengan harga tertinggi

In [22]:
apps_paid[
          apps_paid['Price'] == 0.99
]

                                  App  ...   Android Ver
2171             All-in-One Mahjong 3  ...    4.0 and up
2172   World Racers family board game  ...    5.1 and up
2173    SweetLand — Family Board Game  ...  2.3.3 and up
2244               iBP Blood Pressure  ...    2.2 and up
2275         Blood Pressure Companion  ...    4.1 and up
...                               ...  ...           ...
10586      FL Racing Manager 2015 Pro  ...    3.0 and up
10675     Circle Colors Pack-FN Theme  ...    2.2 and up
10682             Fruit Ninja Classic  ...  4.0.3 and up
10690                        FO Bixby  ...    7.0 and up
10697                         Mu.F.O.  ...    2.3 and up

[106 rows x 13 columns]

List apps dengan harga termurah yaitu 0.99

In [23]:
apps_paid.sort_values('Price', ascending = False).head(5)

                                 App   Category  ...  Current Ver   Android Ver
4367        I'm Rich - Trump Edition  LIFESTYLE  ...        1.0.1    4.1 and up
5356               I Am Rich Premium    FINANCE  ...          1.6    4.0 and up
4362                      💎 I'm rich  LIFESTYLE  ...        1.0.0    4.4 and up
5364  I am rich (Most expensive app)    FINANCE  ...            2  4.0.3 and up
4197          most expensive app (H)     FAMILY  ...          1.0    7.0 and up

[5 rows x 13 columns]

5 aplikasi dengan harga tertinggi

In [24]:
apps_paid.sort_values('Price', ascending = True).head(5)

                                 App         Category  ...  Current Ver   Android Ver
5777   F05WatchFace for Android Wear     PRODUCTIVITY  ...        7.0.1    4.3 and up
4003         Neon Glow C - Icon Pack  PERSONALIZATION  ...        4.5.0  4.0.3 and up
10035                     Deus Ex GO           FAMILY  ...   2.1.111374    4.2 and up
4034                   Hitman Sniper             GAME  ...   1.7.110758    4.1 and up
4047              Koi Live Wallpaper  PERSONALIZATION  ...          1.9    2.2 and up

[5 rows x 13 columns]

5 aplikasi dengan harga terendah

# Count each apps in a category

In [25]:
data_categroy = df.groupby('Category').count()

In [26]:
data_categroy

                      App  Rating  ...  Current Ver  Android Ver
Category                           ...
ART_AND_DESIGN         61      61  ...           61           61
AUTO_AND_VEHICLES      73      73  ...           73           73
BEAUTY                 42      42  ...           42           42
BOOKS_AND_REFERENCE   178     178  ...          178          178
BUSINESS              303     303  ...          303          303
COMICS                 58      58  ...           58           58
COMMUNICATION         328     328  ...          328          328
DATING                195     195  ...          195          195
EDUCATION             155     155  ...          155          155
ENTERTAINMENT         149     149  ...          149          149
EVENTS                 45      45  ...           45           45
FAMILY               1746    1746  ...         1746         1746
FINANCE               323     323  ...          323          323
FOOD_AND_DRINK        109     109  ...          109          109
GAME                 1097    1097  ...         1097         1097
HEALTH_AND_FITNESS    297     297  ...          297          297
HOUSE_AND_HOME         76      76  ...           76           76
LIBRARIES_AND_DEMO     64      64  ...           64           64
LIFESTYLE             314     314  ...          314          314
MAPS_AND_NAVIGATION   124     124  ...          124          124
MEDICAL               350     350  ...          350          350
NEWS_AND_MAGAZINES    233     233  ...          233          233
PARENTING              50      50  ...           50           50
PERSONALIZATION       312     312  ...          312          312
PHOTOGRAPHY           317     317  ...          317          317
PRODUCTIVITY          351     351  ...          351          351
SHOPPING              238     238  ...          238          238
SOCIAL                259     259  ...          259          259
SPORTS                319     319  ...          319          319
TOOLS                 733     733  ...          733          733
TRAVEL_AND_LOCAL      226     226  ...          226          226
VIDEO_PLAYERS         160     160  ...          160          160
WEATHER                75      75  ...           75           75

[33 rows x 12 columns]

In [27]:
df_category = df.Category.value_counts().reset_index()

In [28]:
df_category.rename(columns={'index' : 'Category', 'Category' : 'Total'})

               Category  Total
0                FAMILY   1746
1                  GAME   1097
2                 TOOLS    733
3          PRODUCTIVITY    351
4               MEDICAL    350
5         COMMUNICATION    328
6               FINANCE    323
7                SPORTS    319
8           PHOTOGRAPHY    317
9             LIFESTYLE    314
10      PERSONALIZATION    312
11             BUSINESS    303
12   HEALTH_AND_FITNESS    297
13               SOCIAL    259
14             SHOPPING    238
15   NEWS_AND_MAGAZINES    233
16     TRAVEL_AND_LOCAL    226
17               DATING    195
18  BOOKS_AND_REFERENCE    178
19        VIDEO_PLAYERS    160
20            EDUCATION    155
21        ENTERTAINMENT    149
22  MAPS_AND_NAVIGATION    124
23       FOOD_AND_DRINK    109
24       HOUSE_AND_HOME     76
25              WEATHER     75
26    AUTO_AND_VEHICLES     73
27   LIBRARIES_AND_DEMO     64
28       ART_AND_DESIGN     61
29               COMICS     58
30            PARENTING     50
31               EVENTS     45
32               BEAUTY     42

Kategori family dengan apps terbanyak

## Most Downloaded apps

In [29]:
df.head()

                                                 App  ...   Android Ver
0     Photo Editor & Candy Camera & Grid & ScrapBook  ...  4.0.3 and up
1                                Coloring book moana  ...  4.0.3 and up
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ...  4.0.3 and up
3                              Sketch - Draw & Paint  ...    4.2 and up
4              Pixel Draw - Number Art Coloring Book  ...    4.4 and up

[5 rows x 13 columns]

In [30]:
df.Installs.replace('[\+,]','', regex=True, inplace = True)

In [31]:
df.head()

                                                 App  ...   Android Ver
0     Photo Editor & Candy Camera & Grid & ScrapBook  ...  4.0.3 and up
1                                Coloring book moana  ...  4.0.3 and up
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ...  4.0.3 and up
3                              Sketch - Draw & Paint  ...    4.2 and up
4              Pixel Draw - Number Art Coloring Book  ...    4.4 and up

[5 rows x 13 columns]

In [32]:
df.Installs = df.Installs.apply(lambda x: int(x))

In [33]:
df.sort_values('Installs', ascending=False).head(5)

                                           App  ...         Android Ver
451                                      Gmail  ...  Varies with device
3665                                   YouTube  ...  Varies with device
382   Messenger – Text and Video Chat for Free  ...  Varies with device
386                                   Hangouts  ...  Varies with device
391              Skype - free IM & video calls  ...  Varies with device

[5 rows x 13 columns]

# Rata - rata rating pada tiap kategori

In [38]:
df.head()

                                                 App  ...   Android Ver
0     Photo Editor & Candy Camera & Grid & ScrapBook  ...  4.0.3 and up
1                                Coloring book moana  ...  4.0.3 and up
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ...  4.0.3 and up
3                              Sketch - Draw & Paint  ...    4.2 and up
4              Pixel Draw - Number Art Coloring Book  ...    4.4 and up

[5 rows x 13 columns]

In [46]:
data_rating = df.groupby('Category').mean()

In [41]:
data_rating

                       Rating      Installs
Category
ART_AND_DESIGN       4.377049  2.036526e+06
AUTO_AND_VEHICLES    4.190411  7.278055e+05
BEAUTY               4.278571  6.408619e+05
BOOKS_AND_REFERENCE  4.346067  1.079377e+07
BUSINESS             4.121452  3.306165e+06
COMICS               4.155172  9.661397e+05
COMMUNICATION        4.158537  9.953427e+07
DATING               3.970769  1.355360e+06
EDUCATION            4.389032  5.621626e+06
ENTERTAINMENT        4.126174  1.925611e+07
EVENTS               4.435556  3.544313e+05
FAMILY               4.192383  5.874944e+06
FINANCE              4.131889  2.713970e+06
FOOD_AND_DRINK       4.166972  2.511722e+06
GAME                 4.286326  3.198347e+07
HEALTH_AND_FITNESS   4.277104  5.330156e+06
HOUSE_AND_HOME       4.197368  2.218184e+06
LIBRARIES_AND_DEMO   4.179688  9.544219e+05
LIFESTYLE            4.094904  1.711978e+06
MAPS_AND_NAVIGATION  4.051613  5.840867e+06
MEDICAL              4.189143  1.520159e+05
NEWS_AND_MAGAZINES   4.132189  3.217258e+07
PARENTING            4.300000  6.223222e+05
PERSONALIZATION      4.335256  7.453019e+06
PHOTOGRAPHY          4.192114  3.182411e+07
PRODUCTIVITY         4.211396  4.038766e+07
SHOPPING             4.259664  1.364635e+07
SOCIAL               4.255598  5.432371e+07
SPORTS               4.223511  5.489440e+06
TOOLS                4.047203  1.562104e+07
TRAVEL_AND_LOCAL     4.109292  3.039318e+07
VIDEO_PLAYERS        4.063750  3.888686e+07
WEATHER              4.244000  5.681287e+06

# Jumlah apps pada tiap genre

In [49]:
df_genre = df.Genres.value_counts().reset_index()

In [50]:
df_genre.rename(columns={'index' : 'Genres', 'Category' : 'Total'})

                          Genres  Genres
0                          Tools     732
1                  Entertainment     533
2                      Education     468
3                         Action     358
4                   Productivity     351
..                           ...     ...
110  Music & Audio;Music & Video       1
111          Racing;Pretend Play       1
112     Communication;Creativity       1
113            Comics;Creativity       1
114     Role Playing;Brain Games       1

[115 rows x 2 columns]

# Mean, median, modus by genre

In [61]:
data_genre1 = df.groupby('Genres')['Rating'].mean()

In [63]:
data_genre1

Genres
Action                                   4.285475
Action;Action & Adventure                4.311765
Adventure                                4.180822
Adventure;Action & Adventure             4.423077
Adventure;Brain Games                    4.600000
                                           ...
Video Players & Editors                  4.063924
Video Players & Editors;Creativity       4.100000
Video Players & Editors;Music & Video    4.000000
Weather                                  4.244000
Word                                     4.410714
Name: Rating, Length: 115, dtype: float64

In [79]:
data_genre2 = df.groupby('Genres')['Rating'].median()

In [80]:
data_genre2

Genres
Action                                   4.3
Action;Action & Adventure                4.3
Adventure                                4.3
Adventure;Action & Adventure             4.5
Adventure;Brain Games                    4.6
                                        ...
Video Players & Editors                  4.2
Video Players & Editors;Creativity       4.1
Video Players & Editors;Music & Video    4.0
Weather                                  4.3
Word                                     4.4
Name: Rating, Length: 115, dtype: float64

In [72]:
data_genre3 = df.mode()

In [73]:
data_genre3

      App Category  Rating  ...    Last Updated         Current Ver  Android Ver
0  ROBLOX   FAMILY     4.4  ...  August 3, 2018  Varies with device   4.1 and up

[1 rows x 13 columns]

In [81]:
df.groupby(['Genres'])['Rating'].agg(pd.Series.mode)

Genres
Action                                   4.3
Action;Action & Adventure                4.3
Adventure                                4.4
Adventure;Action & Adventure             4.5
Adventure;Brain Games                    4.6
                                        ...
Video Players & Editors                  4.3
Video Players & Editors;Creativity       4.1
Video Players & Editors;Music & Video      4
Weather                                  4.2
Word                                     4.7
Name: Rating, Length: 115, dtype: object